config/routes.rb
Booking::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :playgrounds

  post 'city/change', to: 'cities#change'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :regions, dependent: :destroy
  has_many :playgrounds

  validates :name, presence: true

end

app/models/cover.rb
class Cover < ActiveRecord::Base
  validates :name, presence: true
end

app/models/infrastructure.rb
class Infrastructure < ActiveRecord::Base

  validates :name, presence: true
end

app/models/playground.rb
class Playground < ActiveRecord::Base
  belongs_to :region
  belongs_to :roof
  belongs_to :cover
  belongs_to :sport_type
  has_many :reviews, inverse_of: :playground
  has_many :assets, dependent: :destroy

  validates_associated :region, :roof, :cover, :sport_type
  validates :name, length: {minimum: 1}
  validates :name, presence: true
end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :city
  has_many :playgrounds
  validates :name, :city_id, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :playground

  validates_associated :playground
end

app/models/roof.rb
class Roof < ActiveRecord::Base

  validates :name, presence: true
end

app/models/sport_type.rb
class SportType < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def change
    cookies[:city_id] = {value: params[:city_id]['0'], expires: 1.week.from_now}
    redirect_to :back
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def index
    @city = City.find(cookies[:city_id].to_i)
    @infrastructures = Infrastructure.all
    @covers = Cover.all
    @playgrounds = @city.playgrounds.page(params[:page]).per(params[:per_page])
  end

  def show
    @playground = Playground.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li> О сервисе</li>
    <li> Правила</li>
    <li> Оплата</li>
    <li> Контакты</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to('Brand', root_path, {class: 'navbar-brand'}) %>
      </div>
      <%= form_tag "/city/change", {method: "post", class: 'navbar-form navbar-lef', role: 'search'} do %>
          <div class="form-group">
            <%= collection_select(:city_id, 0, City.all, :id, :name, {:selected => cookies[:city_id]}, {onchange: "this.form.submit();", class: 'form-control'}) %>
          </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booking</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= yield :stylesheets %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container body">
  <%= yield %>
</div>
<div class="clearfix"></div>

<!--    <%= render 'layouts/footer' %>-->
</body>
</html>

app/views/playgrounds/_filters.html.erb
<div class="well">
  <%= form_for(:playground, method: 'get') do %>
      <div class="form-group">
        <h5><%= I18n.t 'time' %></h5>
        <%= label(:playground, :start_time) %>
        <%= text_field(:playground, :start_time, {value: '07:00', type: 'time'}) %>
        <%= label(:playground, :end_time) %>
        <%= text_field(:playground, :end_time, {value: '23:59', type: 'time'}) %>
        <input type="text" class="slider-time" value=""
               data-slider-min="0"
               data-slider-max="24"
               data-slider-step="1"
               data-slider-value="[7,10 ]"
               data-slider-orientation="horizontal"
               data-slider-selection="after"
               data-slider-tooltip="show">
      </div>
      <hr/>
      <div class="form-group">
        <h5><%= I18n.t 'price' %></h5>

        <%= text_field(:playground, :min_price, {value: '0', type: 'number'}) %>
        <%= text_field(:playground, :max_price, {value: '2000', type: 'number'}) %>
        <input type="text" class="slider-price" value=""
               data-slider-min="0"
               data-slider-max="2000"
               data-slider-step="50"
               data-slider-value="[0,2000]"
               data-slider-orientation="horizontal"
               data-slider-selection="after"
               data-slider-tooltip="show">
      </div>

      <hr/>
      <div class="form-group roof">
        <h5><%= I18n.t 'roof' %></h5>
        <%= collection_radio_buttons(:roof, :name, Roof.all, :id, :name) %>
      </div>

      <hr/>
      <div class="form-group infrastructure">
        <h5><%= I18n.t 'infrastructure' %></h5>
        <%= collection_check_boxes(:infrastructure, :name, Infrastructure.all, :id, :name) %>
      </div>
      <hr/>
      <div class="form-group cover">
        <h5><%= I18n.t 'cover' %></h5>
        <%= collection_check_boxes(:infrastructure, :name, Cover.all, :id, :name) %>
      </div>
  <% end %>
</div>

app/views/playgrounds/index.html.erb
<div class="row">
  <div class="col-md-3 left-filter">
    <%= render 'filters' %>
  </div>
  <div class="col-md-offset-1 col-md-8">
  <% @playgrounds.each do |playground| %>
        <div class="row">
          <div class="col-md-3">
          </div>
          <div class="col-md-6">
            <%= link_to playground_path(playground), class: 'itm-link' do %>
                <%= playground.name %> (<%= playground.sport_type.name %>)
            <% end %>
            <table class="table table-bordered">
              <tr>
                <td><%= I18n.t 'playground.address'%></td>
                <td><%= playground.address %></td>
              </tr>
              <tr>
                <td><%= I18n.t 'playground.cover'%></td>
                <td><%= playground.cover.name %></td>
              </tr>
            </table>
          </div>
          <div class="col-md-3">
            <div><%= I18n.t 'playground.rating' %></div>
            <div> Цена от <%= playground.min_price %> сом/час</div>
          </div>
        </div>
    <% end %>
    <%= paginate @playgrounds %>
  </div>
</div>

app/views/playgrounds/show.html.erb
<%= @playground.name %>
<div class="row">
  <div class="col-md-9">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#characteristics" role="tab" data-toggle="tab">Характеристики</a></li>
      <li><a href="#description" role="tab" data-toggle="tab">Описание</a></li>
      <li><a href="#payment" role="tab" data-toggle="tab">Способы оплаты</a></li>
      <li><a href="#ask-question" role="tab" data-toggle="tab">Задать вопрос</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade" id="characteristics">

        <div class="row">
          <p class="col-md-3">Виды спорта:</p>

          <p class="col-md-9"><%= @playground.sport_type.name %></p>
        </div>
        <div class="row">
          <p class="col-md-3">Размер:</p>

          <p class="col-md-9"><%= @playground.size %></p>
        </div>
        <div class="row">
          <p class="col-md-3">Макс. кол-во игроков:</p>

          <p class="col-md-9"><%= @playground.max_players %></p>
        </div>
        <div class="row">
          <p class="col-md-3">Тип площадки:</p>

          <p class="col-md-9"><%= @playground.roof.name %></p>
        </div>
        <div class="row">
          <p class="col-md-3">Покрытие:</p>

          <p class="col-md-9"><%= @playground.cover.name %></p>
        </div>
        <div class="row">
          <p class="col-md-3">Инфраструктура:</p>

          <p class="col-md-9"></p>
        </div>
      </div>

      <div class="tab-pane fade" id="description">
        <p><%= @playground.description %></p>
      </div>
      <div class="tab-pane fade" id="payment">

      </div>
      <div class="tab-pane fade" id="ask-question">

      </div>
    </div>
    <div>
      <h3>Отзывы</h3>
      <ul>
        <li>
          <% @playground.reviews.each do |review| %>
              <div class="row">
                <div class="col-md-offset-5"><%= review.created_at.to_s(:db) %></div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <p>Площадка <span><%= review.field_rating %> </span></p>
                </div>

                <div class="col-md-3">
                  <p>Инфраструктура <span><%= review.infrastructure_rating %> </span></p>
                </div>

                <div class="col-md-3">
                  <p>Персонал <span><%= review.personal_rating %> </span></p>
                </div>

                <div class="col-md-3">
                  <p>Расположение <span><%= review.location_rating %> </span></p>
                </div>
              </div>
              <div class="row">
                <p class="text-muted">Покрытие:</p>

                <p><%= review.cover_description %></p>

                <p class="text-muted">Инфраструктура:</p>

                <p><%= review.infrastructure_description %></p>

                <p class="text-muted">Общее впечатления:</p>

                <p><%= review.general_impression %></p>
              </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

<%= link_to 'Быстрое бронирование', '#' %>

app/views/welcome/_search.html.erb
<%= form_tag(playgrounds_path, method: 'get') do %>
    <%= collection_select(:sport_type_id, 0, SportType.all, :id, :name) %>
    <%= collection_select(:region_id, 0, Region.all, :id, :name) %>
    <%= time_field(:playground, :start_time) %>
    <%= time_field(:playground, :end_time) %>
    <%= submit_tag(I18n.t 'search') %>
<% end %>